# Generated by Django 3.2.20 on 2023-07-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe'),
        ),
    ]
