# Generated by Django 3.2.20 on 2023-08-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
